prefix : <http://example.org/>

CONSTRUCT {
    ?result :about ?keyword .
}
WHERE {
    ?database a :Database .
    ?request a :SearchRequest ;
        :keyword ?keyword .
    SERVICE ?database {
        ?result :about ?keyword .
    }
}
