prefix : <http://example.org/>
prefix sd: <http://www.w3.org/ns/sparql-service-description#>

CONSTRUCT {
    ?result :about ?keyword .
}
WHERE {
    :database sd:endpoint ?database . # from configuration
    ?request a :SearchRequest ;
        :keyword ?keyword .
    SERVICE ?database {
        ?result :about ?keyword .
    }
}
